# pre-commit钩子配置
# 安装: pre-commit install
# 手动运行: pre-commit run --all-files
# 跳过: git commit --no-verify

repos:
  # Ruff - Python代码检查和格式化
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10    # 与本地安装版本保持一致
    hooks:
      - id: ruff         # linter - 检查代码问题
        args: [--fix]    # 自动修复能修复的问题
      - id: ruff-format  # formatter - 代码格式化

  # 其他有用的钩子
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace  # 删除行尾空格
      - id: end-of-file-fixer    # 确保文件以换行结束
      - id: check-yaml           # 检查YAML语法
      - id: check-added-large-files  # 防止提交大文件
        args: [--maxkb=1000]
        exclude: 'docs/source/tutorial/.*\.ipynb$'  # 教学notebook文件例外
      - id: check-merge-conflict  # 检查合并冲突标记
