eam_al1.cpp
double phi(double r)
对势函数 φ(r) 对于 Al1
φ(r) 分段定义： r ∈ [1.5, 2.3]: exp(a₀ + a₁r + a₂r² + a₃r³) r ∈ (2.3, 3.2]: Σ bₙ(3.2 - r)ⁿ, n = 4..8 r ∈ (2.3, 4.8]: Σ cₙ(4.8 - r)ⁿ, n = 4..8 r ∈ (2.3, 6.5]: Σ dₙ(6.5 - r)ⁿ, n = 4..8 r 原子间距 对势能量
References phi.
Referenced by calculate_eam_al1_energy, phi.
double psi(double r)
电子密度贡献函数 ψ(r)
ψ(r) = Σₖ Cₖ(rₖ - r)⁴ Θ(rₖ - r) 其中 Θ 是 Heaviside 阶跃函数 r 原子间距 电子密度贡献
References psi.
Referenced by calculate_eam_al1_energy, calculate_eam_al1_forces, psi.
double Phi(double rho)
嵌入能函数 F(ρ)
F(ρ) = -√ρ + Σₙ Dₙ(ρ - 16)ⁿ，对于 ρ ≥ 16 F(ρ) = -√ρ，对于 ρ < 16 rho 局域电子密度 嵌入能
Referenced by calculate_eam_al1_energy.
double phi_grad(double r)
对势函数的导数 φ'(r)
Referenced by calculate_eam_al1_forces.
double psi_grad(double r)
电子密度 ψ(r) 的导数 ψ'(r)
Referenced by calculate_eam_al1_forces.
double Phi_grad(double rho)
嵌入能函数的导数 F'(ρ)
Referenced by calculate_eam_al1_forces.
void calculate_eam_al1_energy(int num_atoms, const double *positions, const double *box_lengths, double *energy)
计算系统的总能量
References Phi, phi, psi.
void calculate_eam_al1_forces(int num_atoms, const double *positions, const double *box_lengths, double *forces)
计算所有原子的力
References Phi_grad, phi_grad, psi, psi_grad.