name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Ruff
      run: pip install ruff
    
    - name: Run Ruff linter
      run: |
        ruff check . --output-format=github
        
    - name: Check formatting
      run: |
        ruff format --check .