name: Test

on: 
  push:
    branches: [ main, refactor/v4.0 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Build C++ libraries
      run: |
        make -f Makefile.libs build_libs
    
    - name: Run tests
      run: |
        pytest tests/ -v