name: Test

on: 
  push:
    branches: [ main, refactor/v4.0 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake
    
    - name: Set up virtual environment and install project
      run: |
        uv venv
        uv pip install -e .
        uv pip install pytest
    
    - name: Run tests
      run: |
        uv run pytest tests/ -v